# Generated by Django 2.2.1 on 2019-05-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
