# Generated by Django 2.2.1 on 2019-05-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependencies', '0002_auto_20190507_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('video_link', models.URLField()),
                ('notes', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dependencies.Dependent')),
            ],
        ),
    ]
