# Generated by Django 2.2.1 on 2019-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='doctor_number',
            field=models.CharField(max_length=50),
        ),
    ]
