# Generated by Django 2.2.1 on 2019-05-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_content', '0001_initial'),
        ('dependencies', '0002_auto_20190507_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='sports_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media_content.SportsCategory'),
        ),
    ]
