# Generated by Django 2.2.1 on 2019-05-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='Event',
        ),
    ]
